@Day1WebApi_HostAddress = http://localhost:5198
@AccessToken = CfDJ8CdmO7BRiEhNhpJEDHdQK8W4FJxdaFL-AQhgYaVeKGyIeLCrIcOyOwT1i8h2F3L1q2IOK-vdwsvtKTaEPdDq_AzmPZP7HFdA_bS1cbYxphtZMzANLnXAhUyRS7P9ilq7heYdoQr6fXamxD30uPQl8QYPNWFd4rYzrfKwiD5hH4PAtui8pSwRP9bZLeXHaJvzMvnFBrothBeBUdLM8gnUczB9v708grvBpxEQyRq3jJSd3A5aEqXaNH13NrDHEQ00TTvGlKeu7NtplcQ8Lv9za_8wWUkflpOWmIww5mbtLUbUFU3_a-4Hw9gCMsm61rzSYcplBAOAfmQlHEWW_2N4M-VojMvhDi0OLdVAk0nJfNWabpd0nn8_midQVbkCYkjM31lzrcHMrLQra53Ib9lBB9_vdSgqqABZccZlNbPcCnh_LhBsDqqQVMKozGA4dG-qF5a0OksY5wHuv6VSaGXexXF9lKfuAgNCF6AVQpI4EAmqs2blOSh2HRkBmVTSmgnwHS_59mTTXBBEUPDY45Hy73UXaxP4EfA5Jsxnz7we-wCeGzLVSslPHePiCIBesqj8b7lJO2x0BVL-H5NxPUYH_if9KmAMQ6Ohcnmg1hHIiT0L5cFgpLQaQPdplS3Lgt41Ppovo-5zJH0Ej8AXMEvZfliVOfxipAPsPWlOxZewgcrnRgpHDAPmN6NInIdOrYPVl4vumdi3VbzfDOWVMdS9og6rrih7jhkHj9ODMA2LgCMfJouz6j45eHCFwoSnP6GLHwqrp0DPg5rtg-MtGe_RmUZ5l078G93v_WxIEsgpLQluXcI1cQxT1_mRsAXopnBAeQ

GET {{Day1WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Day1WebApi_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Password123!"
}

###

POST {{Day1WebApi_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "1236",
  "password": "Password123!"
}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Authorization: Bearer {{AccessToken}}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai/3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3FA85F64-5717-4562-B3FC-2C963F66AFA6",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Pelaksana",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12"
}

####

PUT {{Day1WebApi_HostAddress}}/api/Pegawai/3FA85F64-5717-4562-B3FC-2C963F66AFA6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3FA85F64-5717-4562-B3FC-2C963F66AFA6",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Administrator",
  "gaji": 3000,
  "tanggalMasuk": "2026-08-12"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/role
Content-Type: application/json

{
  "roleName": "Admin"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/manage/assign-role
Content-Type: application/json

{
  "email": "example@example.com",
  "roleName": "Admin"
}

###

GET {{Day1WebApi_HostAddress}}/manage/info
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/api/Account/register-pegawai
Accept: application/json
Content-Type: application/json

{
  "nama": "Budi",
  "nip": "1234",
  "jabatan": "Staff",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12",
  "email": "budi@example.com",
  "password": "Password123!"
}

###

DELETE {{Day1WebApi_HostAddress}}/api/Pegawai/3FA85F64-5717-4562-B3FC-2C963F66AFA6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Day1WebApi_HostAddress}}/api/Account/manage/info-pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

PUT {{Day1WebApi_HostAddress}}/api/Kategori/3fa85f64-5717-4562-b3fc-2c963f66afa6
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "nama": "string"
}