@Day1WebApi_HostAddress = http://localhost:5198
@AccessToken = CfDJ8CdmO7BRiEhNhpJEDHdQK8Xeuo4CFaPxOiEmu-iLc75VfT9ocWvTdyRjSBZOMBPX6Fjyy0SWgOxRaaeRBdTvFhiUi-VAD0G4Cr_FB_K95R72vUnT_qDEtL6mz99LvAkp4i7-dsYzovg0FeVeFoUAjigyIutQWhuqGKh32dKdJkXM7V70efcN9NpX_JZxHLsy2YieM84AscN8MHBGvrSuqTN-O3IY-AHpTwpzPa7qmQSxNSAkyMFd1DUDLIWUyOF2t-EvmVZJYvVLzXgJSrOtt0O1TKchG1ZSOkP5J8ugnWhAGnP4Bc-t1pA4pUMpHoklE8ZoCgL4gMP36x7b7LweFL4aoTLd8F2mz75B3Ga-fHxOnmL5PjVew_kE8QcIyc_XC0sXNqStC4uoUIdsy3SjmCyLH-ooMkB2GjapxVT6_T71x9l-N-RY0U0LNsFIlWe3PUWUImBozxVgSNOv6axdPCwE4RM-ub34QYSGPcFN3ugswd0_coNcWRYlM-am_HVZy30NeOmxp7pp3w50vtIeBa18d8_Xh_DMejtVe7Xggo8k7XsREWL2pbV-dVuG1ak6lDZrhPCZSoNf9katDPDS5NBFD36W-cW2fyvKMu89iSKl6MiFBKOTUPxGEFihHXDtwnMyxF86JV54MN-t4Aq6_sC4qqCTjwnbAUFPuXlIoWgZ-Tm_aI7wddEvFYkTaPxSHmG5uXV9HDI7XbTVcqhzYaJgFhXTsjLla1yCilzLVMXdQGrF8GIYmmUegXA3U0Is_zChvUygD6yXFWChlgt54zTzASvmAkWAXX-WWXOQ--Ek

GET {{Day1WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Day1WebApi_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Password123!"
}

###

POST {{Day1WebApi_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Password123!"
}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Authorization: Bearer {{AccessToken}}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai/3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept: application/json
Authorization: Bearer {{AccessToken}}

####

POST {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa8",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Pelaksana",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/role
Content-Type: application/json

{
  "roleName": "Admin"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/manage/assign-role
Content-Type: application/json

{
  "email": "example@example.com",
  "roleName": "Admin"
}