@Day1WebApi_HostAddress = http://localhost:5198
@AccessToken = CfDJ8CdmO7BRiEhNhpJEDHdQK8VfcYMg8ErL12c2sIYac1NgCLYG_dd1d3CXJCULeVi3UJPf7737qwnbCfT07Of8Au8HKfX1BhXY2wVTGoqeA5zdryNUO_rZYRIny076ZzXBl4ffBRafvYOwjyqPjU-KZHPlkoGdegXJkqGN_jHTWRFOzki9zOWKUAsPKYU0C-0Oy23ABsUhg8AyyPyhQRjEzwoIT-lbhyVJ93fdOSIzgeJiJKTIe1G2etwlnQj_iMRRNihxHWt4q8E211h0ngY-K5tiYx7fuK6jlExXSEGM83Fjp_ZMicP0Wf10PIbLnQdU8veqVH1Jd28FzNmdh7GR9_aH9sGuX_-jFlW5uHthjdtKc2eoGImXtKE0Em4g6z_6rVNKmGVmQ7LbafsQxfPlGaejAlN3YiHpVzhpBiAp3eUvlL53zCR2m7DaRmnq5KsKLh5CDfAoJGeoCWzAh-6p6dgypta6RS66QI-Hapzy78jVHe129zw5f5IB4C-1cjhRTmVylwe0bp0KuejZcczGjcUF7AcN4HykeeXcj9F6WbnIVvzg9mOzkpewetv0FsLFIc2t-ebD2zOD-9XhF4UZ5AirvcUvMX_7UgEaw5ljYmkl78DRIFmt6_2ndz7EXhHqpqu-HUMpyufoES9L0CqSUYdyA0_NbJghHN3KJYeg939zDvGtz1SU5-o08PE6WGkuO7hZfbjSyUhh9KMiIQ40yuDMvFvPsTK74fh0rlWkBn8D0WRj0vUqGcXUDBJjAlxs8TR_3E9d6rk7GmuzvWplVcz5CInOhW-FR98TGWxJk4H-t9_q9sGtOW5ktR5pLEVuOA

GET {{Day1WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Day1WebApi_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Password123!"
}

###

POST {{Day1WebApi_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "1236",
  "password": "Password123!"
}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Authorization: Bearer {{AccessToken}}

####

GET {{Day1WebApi_HostAddress}}/api/Pegawai/3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept: application/json
Authorization: Bearer {{AccessToken}}

####

POST {{Day1WebApi_HostAddress}}/api/Pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa8",
  "nama": "Budi",
  "nip": "1235",
  "jabatan": "Pelaksana",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/role
Content-Type: application/json

{
  "roleName": "Admin"
}

###

POST {{Day1WebApi_HostAddress}}/api/Account/manage/assign-role
Content-Type: application/json

{
  "email": "example@example.com",
  "roleName": "Admin"
}

###

GET {{Day1WebApi_HostAddress}}/manage/info
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Day1WebApi_HostAddress}}/api/Account/register-pegawai
Accept: application/json
Content-Type: application/json

{
  "nama": "Budi",
  "nip": "1234",
  "jabatan": "Staff",
  "gaji": 1000,
  "tanggalMasuk": "2026-08-12",
  "email": "budi@example.com",
  "password": "Password123!"
}

###

DELETE {{Day1WebApi_HostAddress}}/api/Pegawai/3FA85F64-5717-4562-B3FC-2C963F66AFA6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Day1WebApi_HostAddress}}/api/Account/manage/info-pegawai
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
